name: CL-host

on: [push]

jobs:

  ccl:

    runs-on: ubuntu-latest
    timeout-minutes: 45

    steps:
    - uses: actions/checkout@v1
    - name: instal host ccl
      run: |
        wget -q https://github.com/sbcl/sbcl/releases/download/sbcl-1.4.14/ccl-host.tgz
        tar xf ccl-host.tgz
        sudo apt-get -qq update | true
        sudo apt-get -qq install git-restore-mtime
    - name: build
      env:  
        SBCL_MAKE_TARGET_2_OPTIONS: --disable-ldb --disable-debugger
      run: |
        git restore-mtime
        ./make.sh --xc-host='ccl-host/lx86cl64 --batch'
    - name: archive ccl-xc fasls
      run: tar --transform 's,^,ccl-host/,' -cf ccl-host-fasls.tgz obj/from-xc/
    - name: upload ccl-xc archive
      uses: actions/upload-artifact@v3
      with:
        name: xc-host-fasls
        path: ccl-host-fasls.tgz

  sbcl:

    runs-on: ubuntu-latest
    timeout-minutes: 45

    steps:
    - uses: actions/checkout@v1
    - name: instal host sbcl
      run: |
        sudo apt-get -qq update | true
        sudo apt-get -qq install sbcl libcapstone-dev git-restore-mtime
    - name: build
      env:
        SBCL_MAKE_TARGET_2_OPTIONS: --disable-ldb --disable-debugger
      run: |
        git restore-mtime
        ./make.sh --xc-host='sbcl --dynamic-space-size 600MB --lose-on-corruption --disable-ldb --disable-debugger'
    - name: archive sbcl-xc fasls
      run: tar --transform 's,^,sbcl-host/,' -cf sbcl-host-fasls.tgz obj/from-xc/
    - name: upload sbcl-xc archive
      uses: actions/upload-artifact@v3
      with:
        name: xc-host-fasls
        path: sbcl-host-fasls.tgz

  compare-xc-host-fasls:

    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs: [ccl, sbcl]

    steps:
    - name: download xc-host fasls
      uses: actions/download-artifact@v3
      with:
        name: xc-host-fasls
    - name: extract xc-host fasls
      run: |
        tar xf ccl-host-fasls.tgz
        tar xf sbcl-host-fasls.tgz
    - name: compare xc-host fasls
      run: |
        diff -ur sbcl-host/ ccl-host/
