name: Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: A job to run test in OpenBSD
    steps:
    - uses: actions/checkout@v4
    - name: Build
      uses: vmactions/openbsd-vm@v1
      with:
        usesh: true
        prepare: |
          pkg_add sbcl

        run: |

          pwd
          ls -lah
          whoami
          env
          sysctl hw.model
          sysctl hw.ncpu
          sysctl hw.physmem
          sysctl hw.usermem
          
