name: Linux

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy: 
      max-parallel: 2
      matrix:
        options: [--with-sb-thread, --without-sb-thread]
        arch: [x86, x86-64]
        subfeatures: ['']
        include:
          - { arch: x86-64, subfeatures: sse4, options: --with-sb-thread }

      fail-fast: false

    steps:
    - uses: actions/checkout@v1
    - name: instal host sbcl
      run: |
        sudo apt-get -qq update | true
        sudo apt-get -qq install sbcl libcapstone-dev
    - name: instal host gcc-multilib
      if: matrix.arch == 'x86'
      run: sudo apt-get -qq --no-install-recommends install gcc-multilib

    - name: backend-sub-features
      if: matrix.subfeatures == 'sse4'
      run: echo '(lambda (features) (list* :popcnt :sse4 features))' > customize-backend-subfeatures.lisp

    - name: build
      env:
        SBCL_MAKE_TARGET_2_OPTIONS: --disable-ldb --disable-debugger
      run: ./make.sh ${{ matrix.options }} --xc-host='sbcl --dynamic-space-size 500MB --lose-on-corruption --disable-ldb --disable-debugger' --arch=${{ matrix.arch }}
    - name: test
      run: cd tests; ./run-tests.sh
    - name: ansi-test
      run: cd tests; ./ansi-tests.sh
