name: Windows

on: [push]

jobs:
  build:

    runs-on: windows-latest

    strategy:
      matrix:
        include:
          - { sys: mingw64, env: x86_64, arch: x86-64}
          - { sys: mingw32, env: i686, arch: x86}
      fail-fast: false

    defaults:
      run:
        shell: msys2 {0}

    steps:
    - uses: actions/checkout@v1
    - uses: msys2/setup-msys2@v2
      with:
        msystem: ${{matrix.sys}}
        install: mingw-w64-${{matrix.env}}-gcc make diffutils git

    - name: install host sbcl
      shell: pwsh
      run: |
        cinst sbcl -source tools-for-build
    - name: build
      env:
        SBCL_HOME: "/c/Program Files/Steel Bank Common Lisp/1.4.14"
      run: |
        PATH=$PATH:"/c/Program Files/Steel Bank Common Lisp/1.4.14"
        export PATH
        ./make.sh --xc-host='sbcl --lose-on-corruption --disable-ldb --disable-debugger' --arch=${{matrix.arch}}
    - name: make installer
      run: |
        ./make-windows-installer.sh
        mkdir sbcl-windows-installer-${{matrix.arch}}; mv output/*msi sbcl-windows-installer-${{matrix.arch}}
    - name: save installer
      uses: actions/upload-artifact@v1
      with:
        name: sbcl-windows-installer-${{matrix.arch}}
        path: sbcl-windows-installer-${{matrix.arch}}
    - name: tests
      working-directory: tests
      run: ./run-tests.sh
    - name: ansi-tests
      working-directory: tests
      run: ./ansi-tests.sh
